<?php

namespace Database\Seeders\Nico;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class NicoUserSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'テスト管理者',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'), //仮のパスワード
                'is_admin' => true, //管理者権限
                'position_id' => 3, // 例: 正社員
                'department_id' => 1, // 例: グループホーム
                'branch_id' => 1, // 例: 福岡支店
                'shift_role' => 'day', // 例: 日勤（'night', 'both' も可）
                'resignation_date' => null,
                'remember_token' => Str::random(10), //ランダム
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'テスト職員',
                'email' => 'staff@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 4,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 企業社員データ
            [
                'name' => '井手 俊介',
                'email' => 'ide.s@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 1, // 社長
                'department_id' => null,
                'branch_id' => null,
                'shift_role' => 'day',
                'resignation_date' => null, //退職日
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '板谷 倫世',
                'email' => 'itaya.m@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 2, // 副社長
                'department_id' => null,
                'branch_id' => null,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 社員
            [
                'name' => '丸山 美鈴',
                'email' => 'maruyama.m@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 4,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '田中 幸治',
                'email' => 'tanaka.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 4,
                'department_id' => 3,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '西山 眞由美',
                'email' => 'nishiyama.m@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 7,
                'department_id' => 3,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '菊池 薫',
                'email' => 'kikuchi.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 4,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '堀之内 佳樹',
                'email' => 'horinouchi.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 5,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'both',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '檜田 翔',
                'email' => 'hiwada.s@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 6,
                'department_id' => 3,
                'branch_id' => 1,
                'shift_role' => 'both',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 事務
            [
                'name' => '大長 真由美',
                'email' => 'jimu@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 7,
                'department_id' => 4,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '小野本 光莉',
                'email' => 'gyoumu.h@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 7,
                'department_id' => 4,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 訪問看護
            [
                'name' => '山口 明宏',
                'email' => 'yamaguchi.a@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => true,
                'position_id' => 5,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '杉本 京子',
                'email' => 'sugimoto.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 5,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '小田 寛之',
                'email' => 'oda.h@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 5,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '大石 紀子',
                'email' => 'oishi.n@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 5,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '草場 渚',
                'email' => 'kusaba.n@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 5,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'day',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '山口 里枝',
                'email' => 'yamaguchi.r@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 7,
                'department_id' => 2,
                'branch_id' => 1,
                'shift_role' => 'both',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // アルバイト（夜勤メイン）

            [
                'name' => '鉦打 航平',
                'email' => 'shoda.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '田中 洋三', //both
                'email' => 'tanaka.y2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6, // アルバイト
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'both',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '小原 有紀',
                'email' => 'obara.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '横山 龍之介',
                'email' => 'yokoyama.r@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '小原 光騎',
                'email' => 'obara.k@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '河野 禎史',
                'email' => 'kono.t@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '中村 有志',
                'email' => 'nakamura.y2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '大谷 優香',
                'email' => 'otani.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '山﨑 彩聖',
                'email' => 'yamazaki.a@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '新原 裕子',
                'email' => 'nihara.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '池田 悠真',
                'email' => 'ikeda.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '中島 颯太',
                'email' => 'nakashima.s@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '平野 悠吏',
                'email' => 'hirano.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '井上 葉子',
                'email' => 'inoue.y@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '鳥越 成二',
                'email' => 'torigoe.s@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '立野 絢士',
                'email' => 'tateno.j2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '山口 瑠奈',
                'email' => 'yamaguchi.r3@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '足立 新一',
                'email' => 'adachi.s2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '黒田 三代',
                'email' => 'kuroda.m2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '足立 伊都子',
                'email' => 'adachi.i2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '仲泊 元和',
                'email' => 'nakadomari.m2@nico-fukuoka.jp',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'is_admin' => false,
                'position_id' => 6,
                'department_id' => 1,
                'branch_id' => 1,
                'shift_role' => 'night',
                'resignation_date' => null,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
